# basic options
title: Chiristopher Williams
author: Chris
email: chris.w.2@live.com
description: A wonderful site
github_username:  chrisw7
baseurl: "/portfolio"

collections:
   projects:
      output: true
      permalink: /:path

# Build settings
markdown: kramdown
#theme: minima